#!/bin/bash
tempfile=$(mktemp 12temp.XXXXXX)
exec 3>$tempfile
echo "This script writes to temp file $tempfile"
echo "first line" >&3
echo "second line" >&3
echo "last line" >&3
exec 3>&-
echo "Done creating temp file. The contents are : "
cat $tempfile
rm -f $tempfile 2> /dev/null
