#!/bin/bash
# Using an alternative file descriptor
exec 3>testout1
echo "This should display on the monitor"
echo "and this should be stored in the file" >&3
echo "Then this should be on the monitor"
